### ISSUE TITLE
 foreign key lookups result in long running query

### ISSUE THREAD

**Issue by xavella** [randlet/django-listable#6]
Foreign key lookups result in long running query, even on small data set. 

Actually, you may not consider this a bug, depending on your view. Using the Business class and Department class example from the documentation, if you search on field "business" (a key linking Department to Business), the code results in a long query; however if you search on field "business__name" the query is returned in microseconds.

Example data models:

``` python
class Business(models.Model):
    name = models.CharField(max_length=255)

class Department(models.Model):
    name = models.CharField(max_length=255)
    business = models.ForeignKey(Business)
```

Results in a long running search query: 

``` python
class Department(BaseListableView):
    model = models.Department
    fields = ("business")
```

results in a quick search query: 

``` python
class Department(BaseListableView):
    model = models.Department
    fields = ("business__name")
```

**Comment by randlet** [comment]
Hi @xavella,

I'm having trouble reproducing this issue...both queries seem to complete in the same amount of time for me. When you just specify `business` instead of `business__name` django-listable will use the string representation of you rmodel so is it possible that for your specific model the __unicode__ method is doing more database lookups?    It may be that you just need to add some fields to the `select_related` option.

**Comment by werdnav** [comment]
I'm not entirely sure why, but explicitly specifying search_fields results resolves this issue. For example: 

```
class Department(BaseListableView):
    model = models.Department
    fields = ("business")
    search_fields = {
        "business": ("ID__icontains",),
    }
```
Possibly because **icontains** accepts a partial match? (i.e. not triggering a db call for each character typed into the UI?)
